import { Task, Friend, Group, SoundTrack, NotificationItem, StatDayData, ProjectStat } from '@/types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Implement Server Actions & Optimistic UI',
    project: 'Next.js Study',
    priority: 'high',
    dueDate: 'Today',
    completed: false,
    description: 'Build real-time form submission with server action response and optimistic local UI updates.',
    assignedTo: 'Alex Johnson',
  },
  {
    id: 'task-2',
    title: 'Build Route Handler middleware authentication',
    project: 'Next.js Study',
    priority: 'high',
    dueDate: 'Today',
    completed: false,
    description: 'Add bearer token checking and role verification in Edge middleware.',
    assignedTo: 'Alex Johnson',
  },
  {
    id: 'task-3',
    title: 'Review TypeScript strict variance annotations',
    project: 'TypeScript',
    priority: 'medium',
    dueDate: 'Today',
    completed: false,
    description: 'Audit generic type covariance and contravariance in generic state handlers.',
    assignedTo: 'Sarah Connor',
  },
  {
    id: 'task-4',
    title: 'Design GSAP ScrollTrigger timeline choreography',
    project: 'UI Design',
    priority: 'high',
    dueDate: 'Tomorrow',
    completed: false,
    description: 'Refine hero section pinning and typography opacity transitions.',
  },
  {
    id: 'task-5',
    title: 'Configure Web Audio API ambient pink noise synthesizer',
    project: 'Audio Engine',
    priority: 'low',
    dueDate: 'Tomorrow',
    completed: false,
    description: 'Create custom audio buffer node for soothing brown/pink ambient background sound.',
  },
  {
    id: 'task-6',
    title: 'Read Next.js Caching & Revalidation Guide',
    project: 'Next.js Study',
    priority: 'medium',
    dueDate: 'Yesterday',
    completed: true,
    completedAt: '2 hours ago',
    description: 'Studied full-route cache, Data cache, and request memoization.',
  },
  {
    id: 'task-7',
    title: 'Build responsive minimal sidebar navigation',
    project: 'UI Design',
    priority: 'high',
    dueDate: 'Yesterday',
    completed: true,
    completedAt: '5 hours ago',
    description: 'Created icon-only collapsed sidebar with sleek tooltips.',
  },
];

export const INITIAL_FRIENDS: Friend[] = [
  {
    id: 'friend-1',
    name: 'Sarah Chen',
    handle: '@sarahc',
    avatar: '👩🏻‍💻',
    color: '#7209B7', // Violet
    status: 'focusing',
    currentTask: 'Refactoring state machine',
    timerMinutes: 18,
    timerSeconds: 42,
    mode: 'pomodoro',
    isFocusing: true,
  },
  {
    id: 'friend-2',
    name: 'David Kim',
    handle: '@davidk',
    avatar: '👨🏻‍🎨',
    color: '#F77F00', // Amber
    status: 'focusing',
    currentTask: 'UI color palette audit',
    timerMinutes: 34,
    timerSeconds: 12,
    mode: 'pomodoro',
    isFocusing: true,
  },
  {
    id: 'friend-3',
    name: 'Elena Rostova',
    handle: '@elena_r',
    avatar: '👩🏼‍🔬',
    color: '#2A9D8F', // Emerald
    status: 'break',
    currentTask: 'Taking a 5m tea break',
    timerMinutes: 3,
    timerSeconds: 15,
    mode: 'pomodoro',
    isFocusing: false,
  },
  {
    id: 'friend-4',
    name: 'Marcus Vance',
    handle: '@marcus_v',
    avatar: '👨🏽‍💻',
    color: '#0077B6', // Sapphire
    status: 'online',
    currentTask: 'Idle / Planning next sprint',
    timerMinutes: 0,
    timerSeconds: 0,
    mode: 'stopwatch',
    isFocusing: false,
  },
];

export const INITIAL_GROUPS: Group[] = [
  {
    id: 'group-1',
    name: 'Next.js Architecture Study',
    code: '#NX8$2!k',
    description: 'Deep dive into App Router, React Server Components, and Edge functions.',
    category: 'Engineering',
    activeCount: 4,
    customLists: ['Architecture', 'Route Handlers', 'Actions & Caching'],
    members: [
      {
        id: 'user-self',
        name: 'Alex Johnson',
        handle: '@alexdev',
        avatar: '🦊',
        color: '#E63946',
        status: 'focusing',
        timerTime: '23:41',
        currentTask: 'Implement Server Actions',
        isUser: true,
      },
      {
        id: 'friend-1',
        name: 'Sarah Chen',
        handle: '@sarahc',
        avatar: '👩🏻‍💻',
        color: '#7209B7',
        status: 'focusing',
        timerTime: '18:42',
        currentTask: 'Refactoring state machine',
      },
      {
        id: 'friend-2',
        name: 'David Kim',
        handle: '@davidk',
        avatar: '👨🏻‍🎨',
        color: '#F77F00',
        status: 'focusing',
        timerTime: '34:12',
        currentTask: 'UI color palette audit',
      },
      {
        id: 'friend-3',
        name: 'Elena Rostova',
        handle: '@elena_r',
        avatar: '👩🏼‍🔬',
        color: '#2A9D8F',
        status: 'break',
        timerTime: '03:15',
        currentTask: 'Tea break',
      },
    ],
    tasks: [
      {
        id: 'gtask-1',
        title: 'Learn Server Actions & Mutations',
        project: 'Architecture',
        priority: 'high',
        dueDate: 'Today',
        completed: false,
        assignedTo: 'Alex Johnson',
        description: 'Implement optimistic updates with server mutation response handling.',
      },
      {
        id: 'gtask-2',
        title: 'Implement Route Handler authentication',
        project: 'Route Handlers',
        priority: 'medium',
        dueDate: 'Today',
        completed: false,
        assignedTo: 'Sarah Chen',
        description: 'Verify JWT and user permissions in Next.js edge route handlers.',
      },
      {
        id: 'gtask-3',
        title: 'Review cache tag revalidation docs',
        project: 'Actions & Caching',
        priority: 'low',
        dueDate: 'Tomorrow',
        completed: true,
        assignedTo: 'Elena Rostova',
        description: 'Check revalidateTag() vs revalidatePath() behavior.',
      },
    ],
  },
  {
    id: 'group-2',
    name: 'TypeScript Mastery',
    code: '&TS9*mQ?',
    description: 'Advanced types, template literals, conditional types, and performance.',
    category: 'Learning',
    activeCount: 2,
    customLists: ['Generics', 'Type Utilities'],
    members: [
      {
        id: 'user-self',
        name: 'Alex Johnson',
        handle: '@alexdev',
        avatar: '🦊',
        color: '#E63946',
        status: 'focusing',
        timerTime: '23:41',
        currentTask: 'Strict variance study',
        isUser: true,
      },
      {
        id: 'friend-4',
        name: 'Marcus Vance',
        handle: '@marcus_v',
        avatar: '👨🏽‍💻',
        color: '#0077B6',
        status: 'focusing',
        timerTime: '12:05',
        currentTask: 'Generic constraint patterns',
      },
    ],
    tasks: [
      {
        id: 'gtask-4',
        title: 'Master infer keyword in conditional types',
        project: 'Type Utilities',
        priority: 'high',
        dueDate: 'Today',
        completed: false,
        assignedTo: 'Marcus Vance',
        description: 'Write type definitions extracting return types of nested Promise callbacks.',
      },
    ],
  },
  {
    id: 'group-3',
    name: 'Zen Design System',
    code: '^DS4#vR!',
    description: 'Building ultra-minimalist, quiet user interfaces with maximum aesthetic power.',
    category: 'Design',
    activeCount: 3,
    customLists: ['Tokens', 'Components'],
    members: [
      {
        id: 'user-self',
        name: 'Alex Johnson',
        handle: '@alexdev',
        avatar: '🦊',
        color: '#E63946',
        status: 'focusing',
        timerTime: '23:41',
        currentTask: 'Theme color mixing engine',
        isUser: true,
      },
      {
        id: 'friend-2',
        name: 'David Kim',
        handle: '@davidk',
        avatar: '👨🏻‍🎨',
        color: '#F77F00',
        status: 'focusing',
        timerTime: '45:00',
        currentTask: 'Typography hierarchy',
      },
    ],
    tasks: [
      {
        id: 'gtask-5',
        title: 'Refine fluid font-size scaling curves',
        project: 'Tokens',
        priority: 'medium',
        dueDate: 'Today',
        completed: false,
        assignedTo: 'David Kim',
        description: 'Ensure smooth clamp() interpolations across mobile and 4K displays.',
      },
    ],
  },
];

import { SOUND_CATALOG } from '@/features/sounds/sounds';

export const INITIAL_SOUNDS: SoundTrack[] = SOUND_CATALOG;

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Friend Focus Invitation',
    message: 'Sarah Chen invited you to join a 25m Focus Session in Next.js Architecture Study.',
    time: '5m ago',
    type: 'group_invite',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Friend Request',
    message: 'Elena Rostova sent you a friend request.',
    time: '25m ago',
    type: 'friend_request',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Pomodoro Completed',
    message: 'Great job! You completed 25 minutes of focus on "Implement Server Actions".',
    time: '1h ago',
    type: 'timer_complete',
    read: true,
  },
];

export const INITIAL_STATS_WEEK: StatDayData[] = [
  { day: 'Mon', focusMinutes: 180, stopwatchMinutes: 45, sessions: 6, tasksCompleted: 4 },
  { day: 'Tue', focusMinutes: 225, stopwatchMinutes: 60, sessions: 8, tasksCompleted: 5 },
  { day: 'Wed', focusMinutes: 150, stopwatchMinutes: 30, sessions: 5, tasksCompleted: 3 },
  { day: 'Thu', focusMinutes: 270, stopwatchMinutes: 90, sessions: 9, tasksCompleted: 7 },
  { day: 'Fri', focusMinutes: 222, stopwatchMinutes: 80, sessions: 8, tasksCompleted: 6 },
  { day: 'Sat', focusMinutes: 120, stopwatchMinutes: 20, sessions: 4, tasksCompleted: 2 },
  { day: 'Sun', focusMinutes: 90,  stopwatchMinutes: 15, sessions: 3, tasksCompleted: 2 },
];

export const INITIAL_PROJECT_STATS: ProjectStat[] = [
  { name: 'Next.js Study', minutes: 500, color: '#E63946' },
  { name: 'TypeScript', minutes: 252, color: '#7209B7' },
  { name: 'UI Design', minutes: 310, color: '#F77F00' },
  { name: 'Audio Engine', minutes: 120, color: '#2A9D8F' },
];
