import { SoundTrack } from '@/types';

export const SOUND_CATALOG: SoundTrack[] = [
  // Nature Sounds (3 static .opus files in /audio/)
  {
    id: 'rain',
    name: 'Gentle Rain',
    category: 'Nature',
    volume: 65,
    isPlaying: false,
    type: 'file',
    src: '/audio/rain.opus',
    description: 'Steady soothing rainfall',
  },
  {
    id: 'ocean',
    name: 'Ocean Waves',
    category: 'Nature',
    volume: 50,
    isPlaying: false,
    type: 'file',
    src: '/audio/ocean.opus',
    description: 'Rhythmic calming surf',
  },
  {
    id: 'fireplace',
    name: 'Cozy Fireplace',
    category: 'Nature',
    volume: 45,
    isPlaying: false,
    type: 'file',
    src: '/audio/fireplace.opus',
    description: 'Warm gentle hearth crackle',
  },

  // Generated Noise (AudioWorklet)
  {
    id: 'white',
    name: 'Smooth White Noise',
    category: 'Noise',
    volume: 25,
    isPlaying: false,
    type: 'noise',
    noiseType: 'white',
    description: 'Equal energy across frequencies',
  },
  {
    id: 'pink',
    name: 'Soft Pink Noise',
    category: 'Noise',
    volume: 35,
    isPlaying: false,
    type: 'noise',
    noiseType: 'pink',
    description: 'Balanced deeper acoustic spectrum',
  },
  {
    id: 'brown',
    name: 'Deep Brown Noise',
    category: 'Noise',
    volume: 45,
    isPlaying: false,
    type: 'noise',
    noiseType: 'brown',
    description: 'Deep low-frequency rumble',
  },

  // Generated Frequencies (Binaural beats & 852 Hz tone)
  {
    id: 'gamma',
    name: 'Gamma 40 Hz',
    category: 'Frequencies',
    volume: 30,
    isPlaying: false,
    type: 'binaural',
    frequency: 40,
    description: 'Binaural beat (200Hz / 240Hz) for peak cognition',
  },
  {
    id: 'alpha',
    name: 'Alpha 10 Hz',
    category: 'Frequencies',
    volume: 35,
    isPlaying: false,
    type: 'binaural',
    frequency: 10,
    description: 'Binaural beat (200Hz / 210Hz) for relaxed alertness',
  },
  {
    id: 'theta',
    name: 'Theta 6 Hz',
    category: 'Frequencies',
    volume: 35,
    isPlaying: false,
    type: 'binaural',
    frequency: 6,
    description: 'Binaural beat (200Hz / 206Hz) for deep meditation',
  },
  {
    id: 'solfeggio-852',
    name: '852 Hz Tone',
    category: 'Frequencies',
    volume: 20,
    isPlaying: false,
    type: 'tone',
    frequency: 852,
    description: 'Solfeggio pure sine tone for serene balance',
  },
];
